_TESTS_:
  recon:
    - &a1
      _NAME_: Context_tests
      _RETURN_:
        - _NAME_: Context_Attributes_Tests
          _RETURN_:
            - _NAME_: REQUIRED_context_timestamp
              attr: $.context.timestamp
              _RETURN_: attr are present
            - _NAME_: REQUIRED_context_bap_id
              attr: $.context.bap_id
              _RETURN_: attr are present
            - _NAME_: REQUIRED_context_bpp_id
              attr: $.context.bpp_id
              _RETURN_: attr are present
            - _NAME_: REQUIRED_context_transaction_id
              attr: $.context.transaction_id
              _RETURN_: attr are present
            - _NAME_: REQUIRED_context_message_id
              attr: $.context.message_id
              _RETURN_: attr are present
            - _NAME_: REQUIRED_context_version
              attr: $.context.version
              _RETURN_: attr are present
            - _NAME_: REQUIRED_context_bap_uri
              attr: $.context.bap_uri
              _RETURN_: attr are present
            - _NAME_: REQUIRED_context_bpp_uri
              attr: $.context.bpp_uri
              _RETURN_: attr are present
            - _NAME_: REQUIRED_context_ttl
              attr: $.context.ttl
              reg:
                - ^P(?=\\d|T)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+S)?)?$
              optional_vars:
                - on_search
                - on_select
                - on_confirm
                - on_init
                - on_cancel
                - on_track
                - on_update
                - on_status
              _RETURN_: attr are present
        - _NAME_: Context_Enums_Tests
          _RETURN_:
            - _NAME_: VALID_ENUM_context_location_country_code
              attr: $.context.location.country.code
              _RETURN_: attr all in enumList
              enumList:
                - IND
            - _NAME_: VALID_ENUM_context_domain
              attr: $.context.domain
              _RETURN_: attr all in enumList
              enumList:
                - ONDC:NTS10
            - _NAME_: VALID_ENUM_context_action
              attr: $.context.action
              _RETURN_: attr all in enumList
              enumList:
                - recon
                - on_recon
    - &a2
      _NAME_: Message_tests
      _RETURN_:
        - _NAME_: Message_Attributes_Tests
          _RETURN_:
            - _NAME_: REQUIRED_message_orders_id
              attr: $.message.orders[*].id
              _RETURN_: attr are present
            - _NAME_: REQUIRED_message_orders_amount_currency
              attr: $.message.orders[*].amount.currency
              _RETURN_: attr are present
            - _NAME_: REQUIRED_message_orders_amount_value
              attr: $.message.orders[*].amount.value
              _RETURN_: attr are present
            - _NAME_: REQUIRED_message_orders_settlements_id
              attr: $.message.orders[*].settlements[*].id
              _RETURN_: attr are present
            - _NAME_: REQUIRED_message_orders_settlements_status
              attr: $.message.orders[*].settlements[*].status
              _RETURN_: attr are present
            - _NAME_: REQUIRED_message_orders_settlements_payment_id
              attr: $.message.orders[*].settlements[*].payment_id
              _RETURN_: attr are present
            - _NAME_: REQUIRED_message_orders_settlements_amount_currency
              attr: $.message.orders[*].settlements[*].amount.currency
              _RETURN_: attr are present
            - _NAME_: REQUIRED_message_orders_settlements_amount_value
              attr: $.message.orders[*].settlements[*].amount.value
              _RETURN_: attr are present
            - _NAME_: REQUIRED_message_orders_settlements_updated_at
              attr: $.message.orders[*].settlements[*].updated_at
              _RETURN_: attr are present
  on_recon:
    - *a1
    - *a2
_SESSION_DATA_:
  tx: {}
