flows:
  - type: playground
    id: master_search
    meta:
      order: 0
    usecase: Solar Purchase Finance
    tags:
      - WORKBENCH
      - MANDATORY
      - REPORTABLE
    description: Master Search
    config:
      $ref: "./PURCHASE_FINANCE/master_search.yaml"
  - type: playground
    id: solar_purchase_finance_single_redirection
    meta:
      order: 1
    usecase: Solar Purchase Finance
    tags:
      - WORKBENCH
      - MANDATORY
      - REPORTABLE
    description: Solar Purchase Finance Single Redirection
    config:
      $ref: "./PURCHASE_FINANCE/solar_purchase_finance_single_redirection.yaml"
  - type: playground
    id: solar_purchase_finance_foreclosure
    meta:
      order: 2
    usecase: Solar Purchase Finance
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Solar Purchase Finance - Loan Foreclosure
    config:
      $ref: "./PURCHASE_FINANCE/solar_purchase_finance_foreclosure.yaml"
  - type: playground
    id: solar_purchase_finance_pre_part_payment
    meta:
      order: 3
    usecase: Solar Purchase Finance
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Solar Purchase Finance - Pre-Part Payment
    config:
      $ref: "./PURCHASE_FINANCE/solar_purchase_finance_pre_part_payment.yaml"
  - type: playground
    id: solar_purchase_finance_missed_emi_payment
    meta:
      order: 4
    usecase: Solar Purchase Finance
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Solar Purchase Finance - Missed-EMI Payment
    config:
      $ref: "./PURCHASE_FINANCE/solar_purchase_finance_missed_emi_payment.yaml"
