flows:
  - type: playground
    id: Personal_Loan_Foreclosure
    usecase: PERSONAL LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Personal Loan - Loan Foreclosure
    config:
      $ref: ./PERSONAL LOAN/Personal_Loan_Foreclosure.yaml
  - type: playground
    id: Personal_Loan_Foreclosure_WITHOUT_ACCOUNT_AGGREGATOR
    usecase: PERSONAL LOAN
    tags:
      - WORKBENCH
      - WITHOUT_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Personal Loan - Loan Foreclosure
    config:
      $ref: ./PERSONAL LOAN/Personal_Loan_Foreclosure_WITHOUT_ACCOUNT_AGGREGATOR.yaml
  - type: playground
    id: Personal_Loan_Missed_EMI
    usecase: PERSONAL LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Personal Loan - Missed EMI Payment
    config:
      $ref: ./PERSONAL LOAN/Personal_Loan_Missed_EMI.yaml
  - type: playground
    id: Personal_Loan_Missed_EMI_WITHOUT_ACCOUNT_AGGREGATOR
    usecase: PERSONAL LOAN
    tags:
      - WORKBENCH
      - WITHOUT_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Personal Loan - Missed EMI Payment
    config:
      $ref: ./PERSONAL LOAN/Personal_Loan_Missed_EMI_WITHOUT_ACCOUNT_AGGREGATOR.yaml
  - type: playground
    id: Personal_Loan_Pre_Part_Payment
    usecase: PERSONAL LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Personal Loan - Pre-Part Payment
    config:
      $ref: ./PERSONAL LOAN/Personal_Loan_Pre_Part_Payment.yaml
  - type: playground
    id: Personal_Loan_Pre_Part_Payment_WITHOUT_ACCOUNT_AGGREGATOR
    usecase: PERSONAL LOAN
    tags:
      - WORKBENCH
      - WITHOUT_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Personal Loan - Pre-Part Payment
    config:
      $ref: ./PERSONAL
        LOAN/Personal_Loan_Pre_Part_Payment_WITHOUT_ACCOUNT_AGGREGATOR.yaml
  - type: playground
    id: Personal_Loan_With_AA_And_Monitoring_Consent
    usecase: PERSONAL LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Personal Loan with Account Aggregator & monitoring consent
    config:
      $ref: ./PERSONAL LOAN/Personal_Loan_With_AA_And_Monitoring_Consent.yaml
  - type: playground
    id: Personal_Loan_Without_AA_And_Monitoring_Consent
    usecase: PERSONAL LOAN
    tags:
      - WORKBENCH
      - WITHOUT_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Personal Loan flow without Account Aggregator
    config:
      $ref: ./PERSONAL LOAN/Personal_Loan_Without_AA_And_Monitoring_Consent.yaml
  - type: playground
    id: Personal_Loan_Without_Acount_Monitoring
    usecase: PERSONAL LOAN
    tags:
      - WORKBENCH
      - WITH_ACCOUNT_AGGREGATOR
      - REPORTABLE
    description: Personal Loan with Account Aggregator & monitoring consent
    config:
      $ref: ./PERSONAL LOAN/Personal_Loan_Without_Acount_Monitoring.yaml
