flows:
  - type: playground
    id: Buyer_App_Fulfilling_Code_On_Confirm
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Buyer app fulfilling with code in on_confirm
    config:
      $ref: ./Buyer_App_Fulfilling_Code_On_Confirm.yaml
  - type: playground
    id: Buyer_App_Fulfilling_Code_On_Update
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Buyer app fulfilling with code in on_update
    config:
      $ref: ./Buyer_App_Fulfilling_Code_On_Update.yaml
  - type: playground
    id: Physical_Store_Based_Gift_Cards
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Physical store based gift cards
    config:
      $ref: ./Physical_Store_Based_Gift_Cards.yaml
  - type: playground
    id: Seller_App_Fulfilling
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Seller App fulfilling - Standard gift card purchase flow
    config:
      $ref: ./Seller_App_Fulfilling.yaml
  - type: playground
    id: Seller_Cancellation
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Seller Cancellation flow
    config:
      $ref: ./Seller_Cancellation.yaml
  - type: playground
    id: Update_Receiver_Info
    tags:
      - WORKBENCH
      - REPORTABLE
    description: Update Receiver Info flow
    config:
      $ref: ./Update_Receiver_Info.yaml
